# Generated by Django 6.0.3 on 2026-03-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_count', models.IntegerField()),
                ('bathroom_count', models.IntegerField()),
                ('type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('PH', 'PH')], max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('operation', models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent')], default='rent', max_length=100)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
